name: SimpleStructureLoader
main: me.jacobcrofts.simplestructureloader.SimpleStructureLoader
version: 1.0
commands:
  paste:
    description: Paste a structure at your current location
    usage: /paste <filename>
  save:
    description: Save a structure
    usage: /save <filename>