name: SimpleStructureLoader
main: me.jacobcrofts.simplestructureloader.SimpleStructureLoader
version: 1.0
commands:
  test:
    description: Test command
    usage: /test
    aliases: [t]
  save:
    description: Save a structure
    usage: /save <filename>